version: '3'
services:
  streamlit-app:
    build:
      context: ./ # current directory
      dockerfile: frontend/streamlit/Dockerfile
    ports:
      - "8501:8501"
    
    # add both containers to same network
    # docker network create my_network
    networks:
      - flask_streamlit_conn
    # volumes:
    #   - ./app:/app

  flask-ml-api:
    build:
      context: ./
      dockerfile: backend/api/ml/Dockerfile
    ports:
      - "80:80"
    networks:
      - flask_streamlit_conn
    # volumes:
    #   - ./app:/app

networks:
  flask_streamlit_conn:
