version: '3'
services:
  streamlit-app:
    build:
      context: ./frontend/streamlit # current directory
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    
    # add both containers to same network
    # docker network create my_network
    networks:
      - flask_streamlit_conn
    # volumes:
    #   - ./app:/app

  flask-ml-api:
    build:
      context: ./backend
      dockerfile: api/ml/Dockerfile
    ports:
      - "80:80"
    networks:
      - flask_streamlit_conn
    # volumes:
    #   - ./app:/app

  react-app:
    build:
      context: ./frontend/ckd_form
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - flask_streamlit_conn

networks:
  flask_streamlit_conn:
