apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit-app
spec:
  type: LoadBalancer
  selector:
    app: streamlit-app
  ports:
  - protocol: TCP
    port: 80           # Exposed port outside the cluster
    targetPort: 8501    # Port where Streamlit is running inside the container
