#name: Docker Compose Build and Deploy
#
#on:
#  push:
#    branches:
#      - main  # Change to the branch you want to trigger the workflow
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Docker
#        run: |
#          sudo apt-get update
#          sudo apt-get -y install docker.io
#          sudo systemctl start docker
#          sudo systemctl enable docker
#
#      - name: Set up Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#
#      - name: Set up and deploy Docker Compose
#        run: docker-compose up --build
#
#      # - name: Setup AWS
#      #   run: docker-compose -f docker-compose.yml up -d


name: Run pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r path/to/requirements.txt  # Replace with your requirements file path

    - name: Run pytest
      run: pytest path/to/tests  # Replace with your test directory path

