name: Build CKD App

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          PGPASSWORD: postgres
          POSTGRES_DB: ckd  # Primary DB
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  

    - name: Build Docker container for Model API
      run: |
        cd backend
        docker build -t model-api:1.0.0 .

    - name: Build Docker container for Streamlit App
      run: |
        cd frontend/streamlit
        docker build -t streamlit-app:1.0.0 .

    # - name: Install dependencies
    #   run: |
    #     cd backend
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt 

    - name: Create Additional Databases
      env:
        POSTGRES_USER: postgres
        PGPASSWORD: postgres
      run: |
        # Wait for PostgreSQL to be ready
        until pg_isready -h localhost -p 5432 -U "$POSTGRES_USER"; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 1
        done
        # Create additional databases
        psql -h localhost -U "$POSTGRES_USER" -c "CREATE DATABASE dev_ckd;"
        psql -h localhost -U "$POSTGRES_USER" -c "CREATE DATABASE test_ckd;"

    - name: Run pytest
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_ckd
      run: |
        cd backend
        pytest tests
